Repository gcivil-nyu-org/fall2019-cs-gy-6063-team-three, pull requests merged in 2019-11, with the labels that each got.

#96 Functionality for creating high school application
  application/templates/application/application-form.html
  application/templates/application/application-list.html
  application/templates/application/application-overview.html
  application/urls.py
  application/views.py
  dashboard/templates/dashboard/index.html
  register/migrations/0003_auto_20191105_2317.py
Labels: enhancement

#109 changed UI for application form, modified application number
  .travis.yml
  admissions/tests.py
  admissions/views.py
  application/forms.py
  application/migrations/0001_initial.py
  application/models.py
  application/templates/application/application-form.html
  application/templates/application/application-list.html
  application/templates/application/application-overview.html
  application/templates/application/index.html
  application/templates/application/loadPrograms.html
  application/tests.py
  application/urls.py
  application/views.py
  dashboard/templates/dashboard/index.html
  dashboard/urls.py
  high_school/migrations/0001_initial.py
  high_school/models.py
  logIn/tests.py
  register/migrations/0001_initial.py
  register/tests.py
  register/views.py
  static/application/js/application.js
Labels: improve

#122 Application form UI changes, bug fixes
  application/forms.py
  application/templates/application/application-form.html
  application/templates/application/application-list.html
  application/templates/application/application-overview.html
  application/templates/application/index.html
  application/urls.py
  application/views.py
  dashboard/templates/dashboard/index.html
  static/application/css/application.css
Labels: improve

#139 fixed bugs, enhanced functionality for application tab
  application/forms.py
  application/migrations/0005_auto_20191125_1746.py
  application/migrations/0006_auto_20191125_2332.py
  application/models.py
  application/templates/application/application-form.html
  application/templates/application/application-list.html
  application/templates/application/application-overview.html
  application/templates/application/broken.html
  application/templates/application/index.html
  application/tests.py
  application/urls.py
  application/views.py
  static/application/css/application.css
Labels: bug, improve

#140 Admin/Student Dashboard redirection fix
  landingpage/views.py
Labels: bug
