Repository gcivil-nyu-org/fall2019-cs-gy-6063-team-three, pull requests merged in 2019-12, with the labels that each got.

#179 Issue #171 Unauthenticated User as Staff - Fixed
  register/forms.py
  register/templates/register/after_register.html
  register/templates/register/index.html
  register/views.py
  static/register/css/register.css
Labels: bug, enhancement

#181 changed apply functionality, can only apply once
  application/forms.py
  application/migrations/0007_auto_20191203_2250.py
  application/models.py
  application/templates/application/application-form.html
  application/templates/application/application-list.html
  application/templates/application/application-overview.html
  application/tests.py
  application/urls.py
  application/views.py
  requirements.txt
  static/application/js/application.js
Labels: bug, improve

#182 Issues #173, 177 completed
  recommendation/forms.py
  recommendation/templates/recommendation/recommendation_rating.html
  recommendation/tests.py
  recommendation/views.py
  static/recommendation/css/recommendation.css
Labels: bug

#194 Add withdrawn status on the application detail page for Admin User
  admissions/templates/admissions/detail.html
Labels: enhancement

#198 application tab improvements, bug fixes
  application/forms.py
  application/migrations/0008_auto_20191210_0335.py
  application/models.py
  application/templates/application/application-form.html
  application/templates/application/application-overview.html
  application/templates/application/loadPrograms.html
  application/tests.py
  application/views.py
  static/application/css/application.css
  static/application/js/application.js
Labels: improve

#208 Reset program if school if not marked as favorite
  static/application/js/application.js
Labels: bug
